import "./globals.css";
import type { Metadata } from "next";
import { Inter, Open_Sans, Lato, Lora } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const open_sans = Open_Sans({
	weight: ["400", "700"],
	subsets: ["latin"],
	variable: "--font-open-sans",
});

const lato = Lato({
	weight: ["300", "400", "700"],
	subsets: ["latin"],
	variable: "--font-lato",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`${lato.variable}`}>{children}</body>
		</html>
	);
}
