import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SidePanel from "./components/SidePanel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex bg-orange-50 ">
					<aside className="w-64 h-screen ">
						<SidePanel />
					</aside>

					<main className="h-screen flex-1 py-8 pr-8">
						<div className="bg-white min-h-full px-12 py-16">{children}</div>
					</main>
				</div>
			</body>
		</html>
	);
}
