import "../globals.css";
import type { Metadata } from "next";
import Header from "./components/Header";

import CartProvider from "./providers/CartProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="font-body">
				<CartProvider>
					<Header />
					<main>{children}</main>
				</CartProvider>
			</body>
		</html>
	);
}
